#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
if [ -f "/usr/bin/virtualenvwrapper.sh" ]; then
  source /usr/bin/virtualenvwrapper.sh
elif [ -f "/usr/local/bin/virtualenvwrapper.sh" ]; then
  source /usr/local/bin/virtualenvwrapper.sh
fi

if keychain 2> /dev/null; then
    keychain -q --nogui $HOME/.ssh/id_rsa
    source $HOME/.keychain/$HOST-sh
fi

alias kprod='kubectl --context=arn:aws:eks:us-east-1:845156828388:cluster/ls-main-cluster-production'
alias ksb='kubectl --context=arn:aws:eks:us-east-1:845156828388:cluster/ls-main-cluster-sandbox'
alias kst='kubectl --context=arn:aws:eks:us-east-1:571579881413:cluster/ls-main-cluster-staging'
alias kqa='kubectl --context=arn:aws:eks:us-east-1:571579881413:cluster/ls-main-cluster-qa'

if [[ -s "$HOME/.dokku/contrib/dokku_client.sh" ]]; then
  alias dokku='$HOME/.dokku/contrib/dokku_client.sh'
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

if [ -f "$HOME/.asdf/asdf.sh" ]; then
  . $HOME/.asdf/asdf.sh
  # append completions to fpath
  fpath=(${ASDF_DIR}/completions $fpath)
  # # initialise completions with ZSH's compinit
  autoload -Uz compinit
  compinit
fi

export PATH="$HOME/.deta/bin:$PATH"
